sagittarius/urls.py
from django.conf.urls import include, url
from sagittarius.views import SectionView , LinkView , TagView  \
                            , SearchView  , FeedView \
                            , ArticleView , NewsView

urlpatterns = \
[ url( r'^section/(?P<section>[\w-]+)/$'
     , SectionView.as_view(), name='sagittarius_section' )
, url( r'^link/(?P<hash>[0-9a-f]+)/(?P<link>[\w-]+)/$'
     , LinkView.as_view(), name='sagittarius_link' )
, url( r'^tag/(?P<tag>[\w-]+)/$'
     , TagView.as_view(), name='sagittarius_tag' )
, url( r'^search/'
     , SearchView.as_view(), name='sagittarius_search' )
, url( r'^atom/$'
     , FeedView.as_view(), name='sagittarius_atom' )
, url( r'^feed/'  # TODO: use djnago.syndication (page 142)
     , FeedView.as_view(), name='sagittarius_feed' )
, url( r'^(?P<section>[\w-]+)/(?P<hash>[0-9a-f]+)/(?P<article>[\w-]+)/$'
     , ArticleView.as_view(), name='sagittarius_article' )
, url( r'^$'
     , NewsView.as_view(), name='sagittarius_news' )
]

sagittarius/forms.py
from django import forms

class SearchForm(forms.Form):
    QUERY_WIDGET = forms.TextInput(attrs={ 'size'        : '40'
                                         , 'placeholder' : 'type your query' })
    query        = forms.CharField(max_length=60, widget=QUERY_WIDGET)
    search_title = forms.BooleanField( required=False, initial=True
                                     , label='Search Title'         )
    search_body  = forms.BooleanField( required=False, initial=True
                                     , label='Search Content'       )
    search_tag   = forms.BooleanField( required=False, initial=False
                                     , label='Search Tags'           )
    search_case  = forms.BooleanField( required=False, initial=False
                                     , label='Case Sensitive Search' )

    def __init__(self, *args, **kwargs):
        super(SearchForm, self).__init__(*args, **kwargs)
        self.label_suffix = ''
        self.fields['query'].error_messages = { 'required'
                                              : 'You must give a query' }

    def clean_query(self):
        query = self.cleaned_data['query'].strip()
        if not query:
            raise forms.ValidationError('You must input a query')
        return query

sagittarius/templates/sagittarius/article.html
{% extends "sagittarius/sagittarius.html" %}

{% block title %}
{{ article.title }}
{% endblock %}

{% block extra_acc_links %}
  <li><a href="#page_content">Skip to article</a></li>
{% endblock %}

{% block toc %}
<div class="toc">
  <div>Contents</div>
{{ article.content_html|safe }}
<!-- TODO media for alternate formats -->
{% if article.tags %}
  <div>Tags</div>
  <div class="tag_container">
  {% for t in article.tags.all %}
  <a class="tag" href="{{ t.get_absolute_url }}">{{ t.slug }}</a>
  {% endfor %}
  </div>
{% endif %}
</div>  <!-- toc -->
{% endblock %}

{% block content %}
<div class="article" id="page_content"><article>

{{ article.body_html|safe }}

<div class="footer"><footer class="fineprint">
<p>First published on <time datetime="{{ article.pub_date|date:'c' }}">
{{ article.pub_date|date:'l, F jS o - g:iA' }}</time>.
</p>
<p>Last modified on <time datetime="{{ article.mod_date|date:'c' }}">
{{ article.mod_date|date:'l, F jS o - g:iA' }}</time>.
</p>
</footer></div>

</article></div>  <!-- page_content -->
{% endblock %}

sagittarius/templates/sagittarius/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
<title>{% block title %}{% endblock %}</title>
{% with favicon='sagittarius/img/lambda-16x16.png' %}
<link rel="icon" type="image/png"
      href="{{ request.scheme }}{% static favicon %}" />
{% endwith %}
{% with css='sagittarius/css/sagittarius.css' %}
<link rel="stylesheet" type="text/css"
      href="{{ request.scheme }}{% static css %}" />
{% endwith %}
<link rel="alternate" type="application/atom+xml"
      href="{{ atom.full_url }}" title="ATOM feed" />
<meta charset="utf-8" />
<meta name="description" content="{{ site.name }}" />
<meta name="author" content="{{ site.context.author }}" />
{% if site.context.style %}
<style>
{{ site.context.style }}
</style>
{% endif %}
{% block extra_headers %}
<!-- use JS only when it is needed
<script type="text/javascript" src="sagittarius.js"></script> -->
{% endblock %}
</head>
<body>

{% block page_top %}
{% endblock %}

{% block page_main %}
{% endblock %}

{% block page_bottom %}
{% endblock %}

</body>
</html>

sagittarius/templates/sagittarius/news.html
{% extends "sagittarius/sagittarius.html" %}

{% load sagittarius_tags %}

{% block title %}
{{ site.name }}
{% endblock %}

{% block toc %}
<div class="toc">
{{ site.context.motd|safe }}
</div>  <!-- toc -->
{% endblock %}

{% block content %}
<h1>{{ site.name }}</h1>

{{ site.context.news|safe }}

<hr />

{% if article_list %}
{% list_articles %}
{% else %}
<p>There are no articles yet, check often.</p>
{% endif %}

{% endblock %}

sagittarius/templates/sagittarius/paginator-old.html
{% extends "sagittarius/sagittarius.html" %}

{% block title %}
{{ section.title }}
{% endblock %}

{% block content %}
<h1>{{ section.title }}</h1>

<p>{{ section.description }}</p>

<hr />

{% if article_list %}
<ul class="object_list">
  {% for a in article_list %}
  <li><a href="{{ a.get_absolute_url }}">{{ a.title }}</a>
    <div>{{ a.excerpt_html|safe }}</div>
    {% if a.tags %}
    <div>
      {% for t in a.tags.all %}
      <a class="tag" href="{{ t.get_absolute_url }}">{{ t.slug }}</a>
      {% endfor %}
    </div>
    {% endif %}
  </li>
  {% endfor %}
</ul>
  {% if is_paginated %}
<div class="pagination">
    {% if page_obj.has_previous %}
  <a class="page_nav"
     href="?page={{ page_obj.previous_page_number }}">&lt; previous</a>
    {% endif %}
  <span class="page_of">
    page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
  </span>
    {% if page_obj.has_next %}
  <a class="page_nav"
     href="?page={{ page_obj.next_page_number }}">next &gt;</a>
    {% endif %}
</div>
  {% endif %}
{% else %}
<p>There are no articles in this section yet, check often.</p>
{% endif %}

{% endblock %}

sagittarius/templates/sagittarius/sagittarius.html
{% extends "sagittarius/base.html" %}

{% load staticfiles %}
{% load sagittarius_tags %}

{% block page_top %}
<div class="header" id="page_top"><header>

<div id="accessibility_links">
<ul>
{% block extra_acc_links %}
{% endblock %}
  <li><a href="#page_main">Skip to content</a></li>
  <li><a href="#nav">Skip to navigation</a></li>
</ul>
</div>

<div class="topl">
<div class="terminal_logo">
{{ site.context.logo|safe }}
</div>
</div>

<div class="topr">
<div class="search_box">
<div class="qsearch">
<form method="get" action="{% url 'sagittarius_search' %}">
  <input type="text"  size="30"
         name="query" id="id_query" value="" placeholder="type your query" />
  <input type="hidden" id="id_search_title" name="search_title" value="on" />
  <input type="hidden" id="id_search_body"  name="search_body"  value="on" />
  <input type="submit" value="Quick Search" />
</form>
</div>
<p><a href="{% url 'sagittarius_search' %}"
      title="Advanced Search Options">Advanced Search</a></p>
<p><a href="{% url 'sagittarius_atom' %}" title="Atom Feed">
Atom Feed
{% with feed_icon='sagittarius/img/feed-icon-14x14.png' %}
<img class="feed" alt="[Atom Feed]"
     src="{{ request.scheme }}{% static feed_icon %}" />
{% endwith %}
</a></p>
</div>
</div>

<div class="topr">
<div class="security_check">
<!-- security validation: ensure for no information leaks over plain http -->
{% if request.user.is_authenticated %}
<div>You're logged in as <strong>{{ request.user.username }}</strong></div>
{% else %}
<!-- user authentication cookies not leaking -->
{% endif %}
{% if request.session.session_key %}
<div>The session is <em>{{ request.session.session_key }}</em></div>
{% else %}
<!-- session cookies not leaking -->
{% endif %}
</div>
</div>

<div class="nav" id="nav"><nav>
<ul class="navdiv">
  <li>
    <a href="{% url 'sagittarius_news' %}">home</a>
  </li>
{% for msec in menu_sections %}
  <li>
    <a href="{{ msec.get_absolute_url }}">{{ msec.title }}</a>
    {% site_entries msec.articles as msec_site_articles %}
    {% site_entries msec.links    as msec_site_links    %}
    <ul>
    {% for feat in msec_site_articles %}
      <li><a href="{{ feat.get_absolute_url }}">{{ feat.menu_entry }}</a></li>
    {% endfor %}
    {% for link in msec_site_links %}
      <li><a href="{{ link.get_absolute_url }}"
             target="_blank">{{ link.menu_entry }}</a></li>
    {% endfor %}
    </ul>
  </li>
{% endfor %}
</ul>
</nav></div>

</header></div>  <!-- page_top -->
{% endblock %}

{% block page_main %}
<div id="page_main">
{% block toc %}
{% endblock %}

{% block content %}
{% endblock %}
</div>  <!-- page_main    -->
{% endblock %}

{% block page_bottom %}
<div class="footer" id="page_bottom"><footer class="fineprint">

<hr />

{% block copyright_footer %}
<p><a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">
  {% with by_sa='sagittarius/img/by-sa-88x31.png' %}
  <img class="button" alt="[Creative Commons Licence]"
       src="{{ request.scheme }}{% static by_sa %}" /></a>
  {% endwith %}
{{ site.context.copyright }}
</p>
<p>This page is licenced under a <a rel="license"
title="Creative commons page"
href="https://creativecommons.org/licenses/by-sa/4.0/">
Creative Commons Attribution-ShareAlike 4.0 International License</a>.
</p>
<p>All code snippets are licenced under the <a rel="licence"
title="Free Software Foundation"
href="https://www.gnu.org/licenses/quick-guide-gplv3.html">
GNU GPL licence version 3, or (at your option) any later version of the
licence</a>.
</p>
<p>This page is text browser friendly (is yours?).</p>
{% endblock %}

</footer></div>  <!-- page_bottom -->
{% endblock %}

sagittarius/templates/sagittarius/search.html
{% extends "sagittarius/sagittarius.html" %}

{% load sagittarius_tags %}

{% block title %}
Search
{% endblock %}

{% block content %}
<h1>Search</h1>

<form method="get" action="{% url 'sagittarius_search' %}">

<p>
{{ form.query.label_tag}}: {{ form.query }}
<input type="submit" value="Search" />
{% if form.query.errors %}
<div>
  {% for error in form.query.errors %}
  <div class="form_error">{{ error|escape }}</div>
  {% endfor %}
</div>
{% endif %}
</p>

<p>
{{ form.search_title }}{{ form.search_title.label_tag }}
{{ form.search_body  }}{{ form.search_body.label_tag  }}
{{ form.search_tag   }}{{ form.search_tag.label_tag   }}
{{ form.search_case  }}{{ form.search_case.label_tag  }}
</p>

</form>

<hr />

{% if article_list %}
  {% if article_list.has_other_pages %}{% paginate_form %}{% endif %}
{% list_articles %}
  {% if article_list.has_other_pages %}{% paginate_form %}{% endif %}
{% else %}
  {% if query %}
<p>No results</p>
  {% else %}
<p>Type your query above</p>
  {% endif %}
{% endif %}

{% endblock %}

sagittarius/templates/sagittarius/section-old.html
{% extends "sagittarius/sagittarius.html" %}

{% block title %}
Prototype page
{% endblock %}

{% block toc %}
<div class="toc">
  <div>Contents</div>
  <ol>
<li><a href="#crash-asm">Crash course in x86 assembler</a></li>
<li>
  <a href="#h2">code</a>
  <ul>
    <li><a href="#minih">block 1</a></li>
    <li><a href="#minih">block 1</a></li>
  </ul>
</li>
<li><a href="#h2">code</a></li>
  </ol>
  <div>Other Formats</div>
  <ul>
<li><a href="proto/markdown">markdown</a></li>
<li><a href="proto/slides-pdf">Slides (in PDF)</a></li>
<li><a href="proto/slides-tex">LaTeX source for Slides</a></li>
  </ul>
</div>  <!-- toc -->
{% endblock %}

{% block content %}
<h1 id="syscall-asm">Basic assembler system calls in Linux</h1>

{% for s in menu_sections %}
<div>{{ s.slug }}</div>
  {% for e in s.entries.all %}
<div>{{ e.slug }}</div>
  {% endfor %}
<div>{{ site.name }}</div>
{% endfor %}

<hr />

<p>We will discuss how to make system calls to the Linux kernel directly from
machine code.  We will use assembler to produce the machine code, although
writing the machine code itself from it is just a matter of translation.
System calls in assembler are just nameless integers, and we will as well
understand how to find which number correspond to which system call.
</p>

{% for o in article_list %}
<div>This <strong>{{ o.slug }}</strong></div>
<div>{{ o.description }}</div>
<div>{{ o.get_absolute_url }}</div>
{% endfor %}

<div>This <strong>{{ section.slug }}</strong></div>
<div>{{ section.description }}</div>
<div>{{ section.get_absolute_url }}</div>
<div>{{ copyright }}</div>

<div id="page_content">
<h2 id="crash-asm">Crash course in x86 assembler</h2>

<p>Assembler is a simplified way of writing machine code,
</p>

<img alt="[Program Flow]" src="program-flow.png" />

<dl>
<dt><strong>BYTE</strong></dt>
  <dd>8 bits (0 or 1), the smaller piece of memory that can be accessed.</dd>
<dt><strong>WORD</strong></dt>
  <dd>Two bytes, i.e. 16 bits.  Although the term <em>word</em> is often used
to define the size of the <code>unsigned int</code> type on a machine - which
is 16 bits on a 16 bit processor, 32 bit on a 32 bit processor and so on - in
assembler a <em>word</em> is always referred as a piece of memory or register
that has 16 bits.
</dd>
<dt><strong>DWORD</strong></dt>
  <dd>A double word, or two words, or 4 bytes.  The same way as the
<em>word</em>, <em>dword</em> always has a size of 32 bits in assembler.
</dd>
<dt><strong>QWORD</strong></dt>
  <dd>A quad word, or two dwords, or 8 bytes.  In assembler it always has 64
bits.  Several assembler instructions do not work on <em>qwords</em>, with the
notable example of <code>push</code>, this is because there are no machine
instructions defined for such tasks.
</dl>

<p>This webpage is under construction.  Every webpage is always under
construction.  This text shall not stay behind the float.
</p>

<h2>Following all tags will be tested for CSS formatting</h2>

<p><em>CSS formatting</em> will give us </p>
<p><strong>CSS formatting</strong> will give us </p>

<p><a href="http://google.com" title="Google">link with title</a></p>

<p>text surrounding the image
<img src="valid_atom_88x31.png" alt="alt text" title="Title" />
on both sides
</p>

<ul>
<li>Keeping your privacy is hard today.</li>
<li>We will talk about a way of keeping your private messages private.</li>
<li>Email is very easy to spoof, it goes in clear text over the internet.</li>
<li>Moreover, email is trivial to interfere with.
  <ul>
  <li>If I control the email server you send your email through I can change
      your messages as I want.
  </li>
  <li>Even if I do not have access to that server I can still send email
      impersonating you.
  </li>
  </ul>
</li>
</ul>

<blockquote>
  <p>Blockquotes are sometimes useful, they're used to quote text from other
sources e.g. books tha i might be using as base for the information contained.
  </p>
</blockquote>

<p>literal backticks in <code>`code`</code>.</p>

<p>Using the file <code>/usr/include/asm/unistd_32.h</code> for syscall info.
</p>

<pre><code>[~]$ egrep '_write|_exit' /usr/include/asm/unistd_32.h
#define __NR_exit 1
#define __NR_write 4
#define __NR_writev 146
#define __NR_exit_group 252
#define __NR_process_vm_writev 348

[~]$ egrep '_write|_exit' /usr/include/asm/unistd_64.h
#define __NR_write 1
#define __NR_writev 20
#define __NR_exit 60
#define __NR_exit_group 231
#define __NR_process_vm_writev 311
</code></pre>

<pre><code>BITS 64

section  .data                      ; data segment
msg      db  "Hello, world!", 0x0a  ; the string and newline character

section  .text   ; text segment
global   _start  ; default entry point for ELF linking

_start:
; SYSCALL write(1, msg, 14)
  mov  rax, 1    ; write is syscall no. 1
  mov  rdi, 1    ; stdout
  mov  rsi, msg  ; address of the string
  mov  rdx, 14   ; length of string
  syscall

; SYSCALL exit(0)
  mov  rax, 60  ; exit is syscall no. 60
  mov  rdi, 0   ; success
  syscall
</code></pre>

<pre><code>BITS 32

section  .data                      ; data segment
msg      db  "Hello, world!", 0x0a  ; the string and newline character

section  .text   ; text segment
global   _start  ; default entry point for ELF linking

_start:
; SYSCALL write(1, msg, 14)
  mov  eax, 4    ; write is syscall no. 4
  mov  ebx, 1    ; stdout
  mov  ecx, msg  ; address of the string
  mov  edx, 14   ; length of string
  int 0x80       ; interrupt kernel

; SYSCALL exit(0)
  mov  eax, 1  ; exit is syscall no. 1
  mov  ebx, 0  ; success
  int 0x80     ; interrupt kernel
</code></pre>
<p>On 32bit and 64bit machines the system calls are performed in completely different ways.
</p>

<table>
  <caption>
    Registers on little endian architectures
  </caption>
  <thead>
    <tr>
      <th>64 bit register</th>
      <th>32 bit (lower left)</th>
      <th>16 bit (lower left)</th>
      <th>Lower left 8 bits</th>
      <th>Lower right 8 bits</th>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>rax</td>
      <td>eax</td>
      <td>ax</td>
      <td>al</td>
      <td>ah</td>
      <td>Accumulator</td>
    </tr>
    <tr>
      <td>rcx</td>
      <td>ecx</td>
      <td>cx</td>
      <td>cl</td>
      <td>ch</td>
      <td>Counter</td>
    </tr>
    <tr>
      <td>rdx</td>
      <td>edx</td>
      <td>dx</td>
      <td>dl</td>
      <td>dh</td>
      <td>Data</td>
    </tr>
    <tr>
      <td>rbx</td>
      <td>ebx</td>
      <td>bx</td>
      <td>bl</td>
      <td>bh</td>
      <td>Base</td>
    </tr>
    <tr>
      <td>rsp</td>
      <td>esp</td>
      <td>sp</td>
      <td>spl</td>
      <td>-</td>
      <td>Stack Pointer</td>
    </tr>
    <tr>
      <td>rsi</td>
      <td>esi</td>
      <td>si</td>
      <td>sil</td>
      <td>-</td>
      <td>Source Pointer</td>
    </tr>
    <tr>
      <td>rdi</td>
      <td>edi</td>
      <td>di</td>
      <td>dil</td>
      <td>-</td>
      <td>Destination Pointer</td>
    </tr>
    <tr>
      <td>r8</td>
      <td>r8d</td>
      <td>r8w</td>
      <td>r8b</td>
      <td>-</td>
      <td>8th register</td>
    </tr>
    <tr>
      <td>r9</td>
      <td>r9d</td>
      <td>r9w</td>
      <td>r9b</td>
      <td>-</td>
      <td>9th register</td>
    </tr>
    <tr>
      <td>r10</td>
      <td>r10d</td>
      <td>r10w</td>
      <td>r10b</td>
      <td>-</td>
      <td>10th register</td>
    </tr>
    <tr>
      <td>r11</td>
      <td>r11d</td>
      <td>r11w</td>
      <td>r11b</td>
      <td>-</td>
      <td>11th register</td>
    </tr>
    <tr>
      <td>r12</td>
      <td>r12d</td>
      <td>r12w</td>
      <td>r12b</td>
      <td>-</td>
      <td>12th register</td>
    </tr>
    <tr>
      <td>r13</td>
      <td>r13d</td>
      <td>r13w</td>
      <td>r13b</td>
      <td>-</td>
      <td>13th register</td>
    </tr>
    <tr>
      <td>r14</td>
      <td>r14d</td>
      <td>r14w</td>
      <td>r14b</td>
      <td>-</td>
      <td>14th register</td>
    </tr>
    <tr>
      <td>r15</td>
      <td>r15d</td>
      <td>r15w</td>
      <td>r15b</td>
      <td>-</td>
      <td>15th register</td>
    </tr>
    <tr>
      <td>rip</td>
      <td>eip</td>
      <td>dip</td>
      <td>-</td>
      <td>-</td>
      <td>Instruction Pointer (cannot be directly accessed)</td>
    </tr>
  </tbody>
</table>

</div>  <!-- page_content -->
{% endblock %}

sagittarius/templates/sagittarius/section.html
{% extends "sagittarius/sagittarius.html" %}

{% load sagittarius_tags %}

{% block title %}
{{ section.title }}
{% endblock %}

{% block content %}
<h1>{{ section.title }}</h1>

<p>{{ section.description }}</p>

<hr />

{% if article_list %}
  {% if is_paginated %}{% paginate_this %}{% endif %}
{% list_articles %}
  {% if is_paginated %}{% paginate_this %}{% endif %}
{% else %}
<p>There are no articles in this section yet, check often.</p>
{% endif %}

{% endblock %}